# Generated by Django 3.1.7 on 2021-03-31 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klutchecommerce', '0003_auto_20210328_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='produtcts_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='klutchecommerce.products', verbose_name='Products ID'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
