# Generated by Django 3.1.7 on 2021-04-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klutchecommerce', '0004_auto_20210331_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='produtcts_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='produtcts_id',
            field=models.ManyToManyField(related_name='orders_products', to='klutchecommerce.Products'),
        ),
    ]
